### ISSUE TITLE
Could batch files speak?

### ISSUE THREAD

**Issue by lazna** [carlos-montiers/enhancedbatch#15]
[This](https://github.com/tenox7/winsay) could make EB definitely cool ;-)

**Comment by adoxa** [comment]
It doesn't compile as-is with TDM64, so I'm really not bothered to make it work in C.

**Comment by lazna** [comment]
If C compatibility is only problem, I could ask someone else to adapt it.

**Comment by carlos-montiers** [comment]
I implemented in the feature-say branch

**Comment by carlos-montiers** [comment]
I implemented in the `feature-say` branch, for review. For work in gcc was a lot of work.

**Comment by carlos-montiers** [comment]
I implemented in 49edeefea52b0cd4bfa50469df7918bceff3b29f (`feature-say` branch) , for review. For work in gcc was a lot of work.

**Comment by adoxa** [comment]
> Using say.exe often as a voice announcement of output of monitoring batches. It is better than wasting time by stearing on the screen....

I thought that's what `echo ^G` was for...

**Comment by lazna** [comment]
> > Using say.exe often as a voice announcement of output of monitoring batches. It is better than wasting time by stearing on the screen....
> 
> I thought that's what `echo ^G` was for...

The 'echo ^G' is good, usin it in some cases, but have not enough information value. If people doing something in the office and synthetic voice says: "Network device unreachable", people will react differently the if sythetic voice says "Twenty seven devices unreachable" or "Main router unreachable"...

**Comment by adoxa** [comment]
While we sort out how to integrate it, here's a much smaller [`say`](https://github.com/carlos-montiers/enhancedbatch/files/3729249/say.zip) (1024 bytes). It's GUI, so it won't block the command line, and you'll need `start` if you don't want to block in a batch.

**Comment by carlos-montiers** [comment]
Seem that can be more than one voice installed in the system. Can be select programmatically: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms719807(v%3Dvs.85)

On windows 7, the voice is female (Microsoft Anna - English (United States)).

**Comment by carlos-montiers** [comment]
On windows 10, there are two voices:
Microsoft David Desktop - English (United States)
Microsoft Zira Desktop - English (United States)

**Comment by lazna** [comment]
I would be great if specific voice could be selected with the command say, this could bring even more information value into speaked message!

**Comment by carlos-montiers** [comment]
> I would be great if specific voice could be selected with the command say, this could bring even more information value into speaked message!
It will be nice. Seems that all the functions related to this task are in header file sphelper.h. Thus, because is C++ (using oop), it will be take some time for translate the needed functions to raw api using C, like SpEnumTokens or SpFindBestToken.
About the syntax for select the voice I not know what is best? select in `@say` extension or create a new extension for select the voice. What do you think @adoxa ?

**Comment by adoxa** [comment]
Australia has a few more: Mark (US), James & Catherine (AU), George, Hazel & Susan (GB). However, I think David/Zira/Hazel are the only ones available to us (they're the only ones in the `SPCAT_Voice` registry key).

I think `set @voice=name` to set a default and `@say /v name ...` for a one-off. Name will be a case-insensitive substring of the name (I hope); more than one match will simply select the first; invalid will be ignored.

Carlos pointed out that `-p` doesn't work in 10 (which I've confirmed with David & Zira), so I won't bother adding that option to the extension.

**Comment by adoxa** [comment]
Done. It's asynchronous by default, with option `/w` to wait.

**Comment by carlos-montiers** [comment]
Jason this is really nice.
Should be nice that the getter of voice return the same string that is printed with `call @voice /v`

But maybe I think the parameter `/V` should be `/L`

With that should be possible easily print text using different voices without changing permanently the default voice.
```
call @say /v David "I'm David"
call @say /v Mark "I'm Mark"
call @say /v Zira "I'm Zira"
```

Maybe also I think that for set the voice maybe a caller @voice should be useful instead of a setter, maybe not list the voices in the `@say` caller extension, only list in the @voice extension.

Thus:
```
::list all the available voices
call @voice
::set the Zira voice
call @voice "Zira"
```
If is okay it should return errorlevel 0, else it should return errorlevel 1 and print an error message.

How handle ambiguous sets like:
call @voice "Microsoft"
?
I'm not seeing the utility of the /X for xml. I not think process xml is useful here.

@lazna , @german-one Do you have some suggestions about this extensions ?

**Comment by adoxa** [comment]
> Should be nice that the getter of voice return the same string that is printed with `call @voice /v`

Done.

> But maybe I think the parameter `/V` should be `/L`

'V' is for voice, 'L' is for...?

> With that should be possible easily print text using different voices without changing permanently the default voice.

You _can_ do that (if you can't, I must have broken something between testing and pushing). The default is only for EB, not the system.

> If [setting voice] is okay it should return errorlevel 0, else it should return errorlevel 1 and print an error message.

It will set errorlevel (if you use `.cmd`); I won't print a message, that's up to the user.

> How handle ambiguous sets like:
> `call @voice "Microsoft"`
> ?

I said above "more than one match will simply select the first" and the help says "the first match will be used."

> I'm not seeing the utility of the /X for xml. I not think process xml is useful here.

Try `call @say /x "<spell>spell</spell>"`. You can also change the pitch, rate and volume, as well as selecting voices based on attributes. [Reference.](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms717077(v%3dvs.85))

**Comment by carlos-montiers** [comment]
I continues thinking in the xml utility and now I think, why not add rate, pitch, and volume as option parameters? That will increase complexity, thus I think that if that not exist as options, the xml feature should be removed, and if that exist as options, the xml feature should be dropped anyway or left it as an undocumented option.

**Comment by adoxa** [comment]
> [W]hy not add rate, pitch, and volume as option parameters?

Rate maybe; there's no function for pitch; volume defaults to maximum, so making it quieter seems to defeat the purpose. I'd rather just leave it for the XML.

> [T]he xml feature should be removed, and if that exist as options, the xml feature should be dropped anyway or left it as an undocumented option.

Enhanced Batch came about because of the limitations of CMD, so why would you want to intentionally limit something else?

**Comment by carlos-montiers** [comment]
Now that I see the examples I think that can be very useful for structure and customize text speech.
