### ISSUE TITLE
Evaluate support options in the begin or at the end in the caller extensions

### ISSUE THREAD

**Issue by carlos-montiers** [carlos-montiers/enhancedbatch#17]
Currently, the call extensions only accept options as the first argument.

For example this works:
`call @say /N Hello`

but this not works:
`call @say Hello /N`

Thus, my question is: the caller extensions will only accept options as the first argument ? Or the option parameter can support be indicated in any place ?

This is not only a question about the SAY extension, is for define the way of this for the future caller extensions.

**Comment by carlos-montiers** [comment]
I not understand why combine all the remaining arguments, it uses malloc. Why not ever use as text the last argument ? Also I have doubts about the number of times malloc is called, maybe we can have memory leaks, because a new call to say will overwrite the text allocated pointer.

**Comment by adoxa** [comment]
`call @say one two` is two arguments combined into a single `one two` string. `malloc` is called once, as a new call to say will wait for a previous call to finish before doing anything (that's what `WaitForSingleObject` does).
