### ISSUE TITLE
echoing variable created by POPEN

### ISSUE THREAD

**Issue by lazna** [carlos-montiers/enhancedbatch#18]
Perform web example: `set "result=@@vol /?"` than trying to print this multiline variable. `set result` works fine, but `echo %result%` print nothing. What am I doing wrong?

**Comment by adoxa** [comment]
LF functions as a terminator, so use delayed expansion.

**Comment by lazna** [comment]
With `setlocal ENABLEDELAYEDEXPANSION` it echoing only first line of multiline variable

**Comment by adoxa** [comment]
It would help if you actually _used_ delayed expansion.

```
c:\Projects\enhancedbatch>eb set @delayedexpansion=1^&set $result=@@vol /?^&echo !$result!
Displays the disk volume label and serial number, if they exist.

VOL [drive:]
```

**Comment by lazna** [comment]
I see, thanks.

What about to expand "Introduction" section witch such and similar informations? I know you are bussy with the development, but you know all about how is it working internaly, and you are only native english writer here..

**Comment by adoxa** [comment]
Delayed expansion should be basic batch knowledge.

**Comment by lazna** [comment]
Sure it is, but there is no any single work to have use it with echoing heap variables https://www.enhancedbatch.com/docs/behaviors/global-heap-variables/

**Comment by adoxa** [comment]
It's got nothing to do with heap variables, either.

```
c:\Projects\enhancedbatch>set result=@@vol /?&echo !result!
Displays the disk volume label and serial number, if they exist.

VOL [drive:]
```

The problem is the LF, which acts as a terminator.

```
c:\Projects\enhancedbatch>echo print%U+A%ignore
print

c:\Projects\enhancedbatch>echo line one!U+A!line two
line one
line two
```

**Comment by lazna** [comment]
Understand, but this question is about documentation generaly. For example I have googled half of hour for term "heap variable", but still not sure if it is equivalent of "multiline variable" or something else as far as this term does not yet exist in batch files context. Maybe EB is targeted mainly for programming experts who are able to read C code, but if not, i want to notice there is not enough documentation for laics.

**Comment by adoxa** [comment]
"Heap variable" indicates that memory for the variable is allocated within `CMD`'s own memory storage (the heap), rather than in the environment storage. I tend to think of them as "private variables", since only the instance of `CMD` that created them will see them; environment variables are "public" (inherited by child processes). (If it makes you feel any better I looked up "laics". :grin:)

**Comment by lazna** [comment]
Thanks for explanation. I will try to ask questions and create my own "knowledge base" in the future.
