### ISSUE TITLE
Compile some extensions for small size

### ISSUE THREAD

**Issue by carlos-montiers** [carlos-montiers/enhancedbatch#19]
I have this idea: Optimize some extensions differently for save bytes.

Thus, I think we can save some bytes optimizing with -Os the extensions that are not used frequently, for example the related to get windows version info.

The rest of extensions that need high performance I can also use with -O3 the -fomit-frame-pointer option for get more performance.

Mmm, but maybe we save only a few bytes, for all the work of compile separately. But this idea can be useful for other new extensions

**Comment by adoxa** [comment]
Performance is not an issue. Timer is a single API call; the first timerhi calls two API functions and does a calculation, other calls are a single API call. There's no performance to optimise. Likewise with other extensions. If you really want high performance **stop using CMD**. It takes about 100ms just to load EB, so that's a big saving, right there. ;)

I did compile with -Os and x86 crashed; it did work with -fomit-frame-pointer, though. Probably an issue with the inline asm.

**Comment by carlos-montiers** [comment]
`I did compile with -Os and x86 crashed; it did work with -fomit-frame-pointer, though. Probably an issue with the inline asm`
Is possible detect the real cause?

**Comment by adoxa** [comment]
Probably, but don't you _want_ to use -fomit-frame-pointer? I don't see why I should waste time tracking down a bug that only appears under specific circumstances. Assuming, of course, that's the only bug.

**Comment by carlos-montiers** [comment]
Mmm I always use and test the x64 version. maybe other bugs exist in the x86 version.
Maybe we are lacking something in the crt, for example this:
I contribute this next for the tiny c project crt1.c
```
#define _UNKNOWN_APP    0
#define _CONSOLE_APP    1
#define _GUI_APP        2

#define _MCW_PC         0x00030000 // Precision Control
#define _PC_24          0x00020000 // 24 bits
#define _PC_53          0x00010000 // 53 bits
#define _PC_64          0x00000000 // 64 bits

// Sets the current application type
    __set_app_type(_CONSOLE_APP);

    // Set default FP precision to 53 bits (8-byte double)
    // _MCW_PC (Precision control) is not supported on ARM
#if defined __i386__ || defined __x86_64__
    _controlfp(_PC_53, _MCW_PC);
#endif

```

And the test with libspg x86 with custom crt and -Os also fails, thus I think is needed review the x86. That failed integrated in EB and as standalone executable (with custom crt), -Os with gcc crt worked. Thus I believe that we need add something to the crt.

**Comment by carlos-montiers** [comment]
I found the mingw crts here:
https://github.com/mirror/mingw-w64/blob/master/mingw-w64-crt/crt/crtexe.c
https://github.com/mirror/mingw-w64/blob/master/mingw-w64-crt/crt/crtdll.c

Maybe we need add: __security_init_cookie 

Here I found other: https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-crt/crt/crtexe.c
that uses `asm  __volatile__ (`
That can be useful maybe.

**Comment by carlos-montiers** [comment]
Maybe because memcpy count refers to characters instead of bytes ?

**Comment by carlos-montiers** [comment]
I add #pragma GCC optimize ("Os")to all c files and khash.hand using -O3 I get these size and pass all the tests:
x64
66560

x86
62976

Thus with the same trick I change to -Os and interestingly I get this sizes:  x64
 67,072 (little more)

x86
62976 (equal)

But the x86 not pass the test.

Thus my conclusion is that -Os can doing some wrong thing and also you can get even more less bytes and working code for both platforms using #pragma GCC optimize ("Os") in each file but optimizing globally as -O3

**Comment by carlos-montiers** [comment]
I add #pragma GCC optimize ("Os") to all c files and using -O3 I get these size and pass all the tests:
x64
66560

x86
62976

Thus with the same trick I change to -Os and interestingly I get this sizes:  x64
67,072 (little more)

x86
62976 (equal)

But the x86 not pass the test.

Thus my conclusion is that -Os can doing some wrong thing and also you can get even more less bytes and working code for both platforms using #pragma GCC optimize ("Os") in each file but optimizing globally as -O3

**Comment by carlos-montiers** [comment]
I add `#pragma GCC optimize ("Os")` to all c files and using -O3 I get these size and pass all the tests:
x64
66560

x86
62976

Thus with the same trick I change to -Os and interestingly I get this sizes:  x64
67,072 (little more)

x86
62976 (equal)

But the x86 not pass the test.

Thus my conclusion is that -Os can doing some wrong thing and also you can get even more less bytes and working code for both platforms using `#pragma GCC optimize ("Os")` in each file but optimizing globally as -O3
