### ISSUE TITLE
Cmd.exe memory leak

### ISSUE THREAD

**Issue by carlos-montiers** [carlos-montiers/enhancedbatch#2]
Cmd.exe have a memory leak. Using the for instruction of batch every file name accumulates memory, so it keeps resizing storage bigger and bigger. 
For example on iteration 4374082 cmd.exe memory usage is 5.8 GB :astonished:

**Comment by adoxa** [comment]
[Fixed.](https://github.com/carlos-montiers/enhancedbatch/commit/bb8cd556e0a9ca9bead17409d1248e09276297dc)

**Comment by adoxa** [comment]
There's another leak: each name has its own memory allocation. It starts out large, performs the substitution, then resizes to fit. The next name pointer replaces the previous. As with the previous leak, it's not usually noticeable (they're all freed when the loop exits), but `range` could potentially have many more "names" than your usual file search.

**Comment by carlos-montiers** [comment]
Finally fixed ny @adoxa in 0f8e69060b892cc10b719afa14296f2a218d76d0

**Comment by carlos-montiers** [comment]
Fixed by @adoxa in 0f8e69060b892cc10b719afa14296f2a218d76d0

**Comment by carlos-montiers** [comment]
Fixed impressively by @adoxa in 0f8e69060b892cc10b719afa14296f2a218d76d0

**Comment by carlos-montiers** [comment]
Fixed impressively by @adoxa in 0f8e69060b892cc10b719afa14296f2a218d76d0
