### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by lazna** [carlos-montiers/enhancedbatch#24]
Just download a fresh version, unzip, load 'compile.cmd' and got lots of errors. What am I doing wrong?

```
C:\Users\lazna\AppData\Local\Temp\cckCM9Ds.o:dll_enhancedbatch.c:(.text+0x1844): undefined reference to `sbprintf'
C:\Users\lazna\AppData\Local\Temp\cckCM9Ds.o:dll_enhancedbatch.c:(.text+0x1876): undefined reference to `sbprintf'
[...]
C:\Users\lazna\AppData\Local\Temp\ccDd388I.o:patch.c:(.text+0x1a7f): undefined reference to `WriteMemory'
C:\Users\lazna\AppData\Local\Temp\ccDd388I.o:patch.c:(.text+0x1aa2): more undefined references to `WriteMemory' follow
collect2.exe: error: ld returned 1 exit status
```

**Comment by adoxa** [comment]
`compile.cmd` is no longer used, use `mingw32-make` instead.

**Comment by lazna** [comment]
Thanks, but is it somewhere documented? I am never used mingw before...

**Comment by adoxa** [comment]
No, it's another one of those things that you're just assumed to know - there's a `makefile`, so you type `make` (or `mingw32-make`).

**Comment by lazna** [comment]
Wrong assumption, but nevermind: It does working now ;-)
