### ISSUE TITLE
Cursor not hidden properly when @image is used

### ISSUE THREAD

**Issue by carlos-montiers** [carlos-montiers/enhancedbatch#25]
When `@image` is used, sometimes the cursor is not hidden

![image](https://user-images.githubusercontent.com/5741891/71371630-8aa7ea00-2590-11ea-8e77-e78bfca94b3a.png)

**Comment by adoxa** [comment]
Needed to wait a bit for the cursor to actually hide, otherwise it was copied as part of the background.
