### ISSUE TITLE
Error when loading Enhanced Batch

### ISSUE THREAD

**Issue by gaucon** [carlos-montiers/enhancedbatch#29]
I'm using windows Servers 2019 Essential, and I've got the following error when loading Enhanced Batch DLL.
![image](https://user-images.githubusercontent.com/5741891/71552955-fbae2e00-29e4-11ea-8046-35b388fc971b.png)

**Comment by carlos-montiers** [comment]
Hello gaucon, recently in the commit 65c0c78a5525cf5348528a69c1c960b1d6ce1a19 support for the version 10.0.17763.592 was added. Please can you pull the last code changes and test if it works in your windows server 2019 essential?

**Comment by carlos-montiers** [comment]
Hello @gaucon, recently in the commit 65c0c78a5525cf5348528a69c1c960b1d6ce1a19 support for the version 10.0.17763.592 was added. Please can you pull the last code changes and test if it works in your windows server 2019 essential?

**Comment by gaucon** [comment]
Thanks Carlos, I could compile and load without error the Enhanced Batch program.
I've run some of the "demo*.cmd" test and it all work fine.

**Comment by carlos-montiers** [comment]
you welcome @gaucon
