### ISSUE TITLE
Hook CmdBatNotification

### ISSUE THREAD

**Issue by carlos-montiers** [carlos-montiers/enhancedbatch#3]
CmdBatNotification is not hooked correctly in some cmd versions.
This cause the automatic unload of the dll not be executed.

**Comment by german-one** [comment]
On which versions is that happening?
What do you think is the reason for that? Does it help if you don't override the default `_dllstart` routine.

**Comment by adoxa** [comment]
From Windows 8 (6.2) `CmdBatNotification` is called as a stub in another DLL that is delay loaded.

**Comment by german-one** [comment]
Good find. I also read about `CmdBatNotificationStub` in `cmdext.dll`. But since none of them are documented it's quite difficult to find something useful in the internet.
