### ISSUE TITLE
What does `call @clear` do?

### ISSUE THREAD

**Issue by DaveBenham** [carlos-montiers/enhancedbatch#30]
What is the purpose/function of `call @clear`? It seems to clear the screen, but how does it differ from `cls`?

**Comment by adoxa** [comment]
It only clears the window, not the buffer; it can also clear any rectangular region (within the window), using any attribute and color. Try `call @clear /?`.

**Comment by DaveBenham** [comment]
Thanks. I was wondering if there was built in help, and how to access it.
