### ISSUE TITLE
Proposed New /H option for cmd

### ISSUE THREAD

**Issue by DaveBenham** [carlos-montiers/enhancedbatch#34]
This might be a stretch, but it would be nice for a child cmd process to pass heap values back to the parent. This would definitely be useful with pipes and FOR /F, and probably useful in general.

Perhaps it could be implemented by adding an `/H:size` option to cmd that would reserve size space in the parent heap, and then the child cmd would need a way of storing values in the reserved parent heap space. Ideally there would be overrun protection.

Perhaps this would need to be implemented via an `call @cmd /h:size /c command` extension so that the parent could parse the command and reserve the space before the actual `cmd /h:address /c command` was issued.

Or perhaps this is just a zany idea.

**Comment by adoxa** [comment]
Carlos suggested something like that in email; I shot it down, not gonna happen.

**Comment by carlos-montiers** [comment]
There was the idea of provide something like interprocess communication (with events) but I think design that is related to provide async features, that will cause a lot of discussion.
