### ISSUE TITLE
Modify EB label scanning to make it backward compatible with existing scripts

### ISSUE THREAD

**Issue by DaveBenham** [carlos-montiers/enhancedbatch#39]
Enhanced Batch provides some amazing new capabilities to the batch language. But there already exists a large library of batch scripts in the world, and the current advanced batch syntax has the potential to break a lot of existing scripts.

Ideally, existing batch scripts should continue to work if enhanced batch is loaded. I would like to be able to load EB at the beginning of a cmd session and be able to take advantage of the new features both in new scripts, as well as from the command line, and I want to have confidence that existing scripts continue to work.

You could argue I should only load EB within new scripts where I have control over the code. But even if I am writing a new EB enabled batch script, I might want to call a pre-existing script from a library of utility functions, and I want to have confidence that EB will not break the old code.

I see two obvious places where EB runs the risk of breaking existing code:

1) Modified logic when scanning for :labels

2) Modified variable expansion syntax could interfere with existing variable names.
***I moved this 2nd topic to #40 so it can be tracked separately.***

If fixes cannot be made in these two areas, then my interest in the project will be much diminished.

-----

**1** - EB rules for matching a label are very different than the native label scanner.

EB has a very simple rule for scanning for :labels
 - The first character of the line must be a colon, followed immediately by the label
 - I haven't investigated, but I suspect the label stops at the first space or end of line
 
The native scanner rules are significantly more complex:
 - The label colon need not appear at the beginning of the line. If it doesn't, then
   - The first character can be any character other than \x00 or `:`
   - Then may follow 0 or more of any combination of the following
     - \x09 (tab)
     - \x0B (vertical tab)
     - \x0C (form feed)
     - \x0D (carriage return)
     - \x20 (space)
     - `,`
     - `;`
     - `=`
     - \xFF (non-breaking space)
 - Then follows `:` and the Label
 - The label stops at the first occurrence of any of the following (the stop character is not considered part of the label):
     - \x00 (nul)
     - \x09 (tab)
     - \x0A (line feed)
     - \x0D (carriage return)
     - \x20 (space)
     - `&`
     - `+`
     - `:`
     - `<`
     - `>`
     - `|`
 - If the target label specified by GOTO or CALL is 127 characters or more (disregarding any leading `:`) then only the first 127 characters are used, and it matches the first label line where the label starts with those same 127 characters.

I have seen lots of existing code that indents labels, normally with spaces, but I have used  
`===== :label ====` in my code as well. It shouldn't be hard to modify EB to support the native rules for label identification, and still support the EB enhancements (improved speed due to code caching, and backwards scanning)

**Comment by adoxa** [comment]
> EB has a very simple rule for scanning for :labels

That's to make it quick.

> I haven't investigated, but I suspect the label stops at the first space or end of line

That's right.

> The native scanner rules are significantly more complex:

And that's partly why it's slow.

> [...] It shouldn't be hard to modify EB to support the native rules for label identification, and still support the EB enhancements (improved speed due to code caching, and backwards scanning)

Maybe not, but that'll slow it down and defeat the purpose. There is no cache, as it's currently quick enough to scan the file. I might be prepared to ignore leading whitespace, along with any number of `,;=`, but that would be it.

> Heap variable names would be prefixed by `=$`

I think equals itself would qualify as the prefix, so no real need for `$`, too. Then again, the extra distinction between name and value is useful. In any event, using `=` makes creating array variables extremely awkward: `set =$array=$index=value`. Curly expansion makes it look better - `set =$array{=$index}=value` - but the underlying problem remains. Using another two-character prefix would be far easier, maybe `~$` and `~@`?

> Filters would be introduced by `=` after the variable name instead of `;`.

I chose `;` to match `:`, thinking it would be rare enough in variable names to get away with it. I could consider `=`, but it really doesn't look right.

> I know the syntax is not nearly as elegant, but I think backward compatibility is more important than syntax elegance.

Backward compatibility is a double-edged sword and is partly the reason `cmd.exe` is in the mess it's in. I think anyone prepared to use EB should be prepared to modify their existing scripts to work with it.

**Comment by DaveBenham** [comment]
>There is no cache, as it's currently quick enough to scan the file.

OK. I was misled by the following quote from the [Doc pages](https://www.enhancedbatch.com/docs/behaviors/subroutine-features/)

>Improve finding labels
>===============
>In Batch, you can identify subroutines with labels. Normally, work with a label using call or goto is a really slow operation because each time the batch file is read again trying to find the label.
>
>With Enhanced Batch, that is a past thing, because first, the batch file content is saved in the memory, also with the address of each label. Thus, when you request a label it “jumps” directly.

I like the fact that you are not caching, as that could consume significant memory, and it would break the feature that batch code can be self modifying. That feature is rarely used, and perhaps not a good idea, but I like preserving existing functionality when possible.

But what on earth are you doing to achieve such good speed improvements? I ran a test on a 180kb test script with ~2500 lines. Native batch took 2.65 seconds to perform 100 iterations. EB cut the time to .12 seconds, a factor of 22 improvement!

I can't believe the simplified scan rules account for much improvement, but maybe I'm wrong. Please describe your technique - I am really curious.

>I might be prepared to ignore leading whitespace, along with any number of `,;=`, but that would be it.

Thanks, that would be good. I would rank the importance of the old rules as follows:
1 - any number of leading whitespace characters
2 - Additional label stop characters besides whitespace
3 - Allow for any character in position 1 of the label line
4 - Limit label length to 127 characters

If it doesn't slow things down too much, then I would encourage you to also implement the stop characters.

**Comment by carlos-montiers** [comment]
The speedy finding labels will not works if the label is not at the begin of the line.
@adoxa write:
> It must start the line for the search to be successful

 Almost all the batch codes begin the label at the begin of the line, but someones can write some spaces before the :label. Thus I thinks is needed remark in the documentation that is fundamental write the label at the begin of the line.
Also, we are converting the label to multibyte for remove the ascii limit, I only request this for support for example japanase labels batch codes.
Maybe we can create an option for control this, thus only having in our code ascii labels and setting an option for only use ascii labels we can gain more speed.
The commits related to the implementation are:
5c85f24e13c025f2e8d7c65c1dd78fdc51820c56
and
433c4f0e35d944c7184406c316fa16cbcb755df9

**Comment by DaveBenham** [comment]
Could you provide a writeup how it works? or if emails have been written, send me those?

**Comment by DaveBenham** [comment]
OK. I traced the code, and best I can tell, the majority of the speed improvement comes from reducing the I/O cost by reading the entire file all at once as opposed to in pieces. Does that sound correct?

**Comment by adoxa** [comment]
That, not converting to wide and specifically searching for a newline and colon pair. Presumably, I didn't test why it's faster.

**Comment by adoxa** [comment]
> \xFF (non-breaking space)

Technically that is U+00A0, which is usually '\xFF', but not always. I don't support it.

> Then follows `:` and the Label

Whitespace and any of `=,;` can be between the colon and label. I don't support that, either. I also don't support `^` escapes in a label.

> 1 - any number of leading whitespace etc. characters

Done.

> 2 - Additional label stop characters besides whitespace

Done.

> 3 - Allow for any character in position 1 of the label line

Won't do.

> 4 - Limit label length to 127 characters

Won't do. EB's labels can be 512 bytes, but they must end with a delimiter. Specifically, the label in a goto/call line can be any length, but only 512 bytes will be used; the label in the file must end with a terminator. This means a 513-byte label will never be found (by EB; the 127-character version will be found as normal). I can't imagine anyone creating a label greater than a couple of dozen characters.

There may also be case differences; this will not change. It seems there's a couple of bugs in `_wcsicmp` (ignore case in wide string comparisons): Unicode characters < 256 are treated as ANSI characters; and the incorrect code page may be used (my OEM code page is 437, but it maps according to 850, the default for Aus). EB doesn't use `_wcsicmp`, so the labels it matches may be different to the labels CMD matches.

**Comment by DaveBenham** [comment]
Very nice. Thanks,

> > Then follows : and the Label
>
> Whitespace and any of =,; can be between the colon and label. I don't support that, either. I also don't support ^ escapes in a label.

How the hell did I not know about whitespace etc between the colon and the label !!! It makes sense, otherwise something like `: label` could safely be used as a comment. But add a second `:` stop character, and `::comment` is a safe comment (except within parentheses).

I did also forget about the caret escape feature, but knew about it at one time.

Then I did some tests and was amazed to find that it seemed like you did implement all the features. Huh!

After a while I realized that if your patch failed to find the label, then the search fell through to the standard label scanner!!! Of course this does not work when you do a reverse scan because the standard scan is looking for the `~`, whereas you strip it off.

    @echo off
    call eb
    goto :start
    
    : beforeSpace
    :afterSpace
    : bothSpace
    echo call %0 found BEFORE
    exit /b
    
    :start
    call :beforeSpace
    call :afterSpace
    call :bothSpace
    echo(
    call :~beforeSpace
    call :~afterSpace
    call :~bothSpace
    exit /b
    
    :beforeSpace
    : afterSpace
    : bothSpace
    echo call %0 found AFTER
    exit /b

    :~bothSpace
    echo call %0 found actual :~bothSpace label
    exit /b

--OUTPUT--
```
call :beforeSpace found AFTER
call :afterSpace found BEFORE
call :bothSpace found AFTER

call :~beforeSpace found AFTER
call :~afterSpace found BEFORE
call :~bothSpace found actual :~bothSpace label

```


Did you know about this?

So it turns out my concerns were moot - even if your fast scan fails to find the label in existing code, the standard scanner will still eventually find it, albeit a bit slower. Even if existing scripts actually use a `:~label` (not intended to be a backward search), it still works while EB is loaded. This is fantastic - the ultimate in backward compatibility 👍 

So if you revert back to the simpler scanner to achieve a bit better performance, I won't mind. Of course I also won't mind if you keep it as is :-)

**Comment by adoxa** [comment]
> I did also forget about the caret escape feature, but knew about it at one time.

Since both goto and the label must have the carets I probably should have implemented this (it wouldn't take much). ATM given `forward^>label` EB will stop at the `>`, thus `forward^<label` would also match. I figured not many people would know about it and those that did probably wouldn't use it, anyway.

> Did you know about this?

Did I know if EB couldn't find the label it would let CMD do the work? Yes, sorry that wasn't clear.

> So if you revert back to the simpler scanner to achieve a bit better performance, I won't mind. Of course I also won't mind if you keep it as is :-)

Difference was negligible.
