### ISSUE TITLE
Curly brace expansion

### ISSUE THREAD

**Issue by carlos-montiers** [carlos-montiers/enhancedbatch#4]
Implement the new curly brace expansion, that consist on do shell-style substitutions directly during lex stage.
Also add @curlyexpansion extension that will enable/disable it. 
About the format:
`{variableName}`
`{variableName{otherVariable}}`

**Comment by DaveBenham** [comment]
I like this idea a lot as long as `@curlyexpansion` is also implemented to enable/disable it. I believe the default should be curly expansion is disabled to minimize the risk of breaking existing scripts.

**Comment by adoxa** [comment]
In email we've pretty much cancelled the idea. However, a single level of embedded heap variables are expanded (see commit ab493b5).

Curly braces would be expanded either before or after delayed expansion (that's what I would hook).

**Comment by DaveBenham** [comment]
> (see commit ab493b5)

I like that, though I find it a bit difficult to read. Why not implement curly brace expansion within percent and delayed expansion instead. Then it could expand any type of construct - environment variable, heap variable, parameter, or gettable extension.

Assume `%@row%` currently equals 10, and parameter `%1=3`, then

    set $a=1
    set b=2
    set V1.2{3}=hello
    echo [%V{$a}.{b}{{{$1}};{@row}%]

would yield

    [     hello]

**Comment by adoxa** [comment]
Hm, yes, why not indeed? I should have thought of that. Your example won't work, though, since `{3}` will (probably) expand to nothing, there needs to be a way to escape the braces (other than the ugly `{U+7B}`).

**Comment by DaveBenham** [comment]
I simply followed your example of escaping `$` literal as `$$`. So why wouldn't `{{` work as an escape for `{` literal, as long as you expand only 1 level deep (no recursion)?

**Comment by adoxa** [comment]
There is no way I will support `{{` as a literal brace. The original point of brace expansion was for nested expansion, but Carlos seems to have gone off that idea (discussed in email). My primary reason is for when you need a delayed array index, so `!array$i!` is sufficient. However, having something like `!line{@row}!` could be useful.

**Comment by DaveBenham** [comment]
I didn't realize you had already implemented `$var` embedded expansion. The rule of only alpha-numeric chars allowed in the name is awkward to me, and so is the use of `\` to end the embedded expansion when an alpha-numeric immediately follows.

If you implement `{var}` embedded expansion for any purpose, then there is no need to also support `$var` embedded expansion. I think it is easier to document/understand/read `$var{$embedded}x` than `$var$embedded\x`. And the `{}` easily supports `{embedded}` as well as `{@embedded}`.

You were comfortable only doing 1 level of `$embedded` expansion. If that is good enough, then there isn't any need for nested `{embedded}` expansion, and `{{` is sufficient to escape a `{` literal.

But if you want nested embedded `{var}`, then yes, some other escape mechanism is needed, and something would be needed to escape a `}` literal as well.

I recommend `\{` for a `{` literal, and `\}` for a `}` literal.
Of course something would be needed to escape a `\` literal as well - I recommend `\\`.

Finally, once you have made `\` an escape character, you can use it for other escape sequences. You could use `\c` (case insensitive) to represent a `:` literal.

A `\` that is not followed by `}`, `{`, `\`, or `c` could be either treated as a `\` literal, or it could simply be stripped. I think I prefer the latter. That way developers will be forced to adopt and understand the syntax and not run into nasty surprises after getting used to using a `\` literal in most circumstances.

If you do implement embedded `{var}` expansion, then there should be an `@embeddedExpansion` extension to enable/disable the feature, and to get the current state. That way the feature can be disabled if having to call old scripts that happen to use `{` literals in variable names.

The embedded `{var}` expansion should be supported in both percent as well as delayed expansion, though I imagine that largely falls out of your existing design without any extra effort.

If you really wanted to go overboard, then you could also support the various modifiers (filters as they are currently called), as in `{embedded;filter}`, But I don't think that is necessary.
