### ISSUE TITLE
Fix for %cmdcmdline:~n,m% and %cmdline:find:replace% are destructive

### ISSUE THREAD

**Issue by DaveBenham** [carlos-montiers/enhancedbatch#43]
%cmdcmdline% is a dynamic pseudo environment value that should give the command line that was used to launch the current instantiation of cmd.exe. It normally works just fine. But if you do substring or find/replace on the value, then it permanently alters the source value.

For example: `echo(%cmdcmdline:~0,0%` will properly print an empty line. But then a subsequent `echo(%cmdcmdline%` also results in an empty line - the value has been destroyed.

The same destructiveness occurs with `%cmdcmdline:find=replace%`. In fact, if you cause CMDCMDLINE to grow large enough it can overrun the buffer and crash cmd.exe! See https://www.dostips.com/forum/viewtopic.php?f=3&t=4312 for more info.

I believe there may be a simple fix - When you intercept percent and delayed expansion variable expansion, you can check if the variable is CMDCMDLINE, and if it is, then define a true CMDCMDLINE environment variable with the current value, and return to continue with normal processing. CMD.EXE will then work with the environment variable instead of the dynamic value, and substring, find/replace operations will not be destructive.

Normally I discourage overriding dynamic variables, but as long as every expansion always stuffs the current dynamic value into the environment, then it should all work out.

I suppose any true CMDCMDLINE environment variable should be cleared if EB is unloaded.

**Comment by carlos-montiers** [comment]
Thanks I not knowed that bug.
I think that maybe is better create a new extension for get a reliable value of the command line. For example instead of try fix `%f0` we provide a reliable helper: `$0;~` thus in this case for follow the same method we can create a new extension. I think is not good overhead the variable names with a white list. I think that, but @adoxa ?

**Comment by adoxa** [comment]
I think the simplest solution is to detect `cmdcmdline`, check it doesn't exist (subject to whatever happens with #42) and provide our own copy of the command line.

It does raise another issue: dynamic variables can't be filtered. This is a "won't fix" issue, as it's easier to just tell users to make a copy of the variable and filter that.

**Comment by carlos-montiers** [comment]
@adoxa who implement this? cmdcmdline value needs offsets or is GetCommandLine() ?

**Comment by adoxa** [comment]
Neither, it'll be done in `MyGetEnvironmentVariableW`.

**Comment by DaveBenham** [comment]
>It does raise another issue: dynamic variables can't be filtered.

Ouch. That is unfortunate. I just assumed they could be.

But when I think about it, I can see why filtering dynamic pseudo variables could be a problem - You would have to write a dedicated routine for each individual pseudo variable. It could be done, but I can see why you don't want to.

**Comment by carlos-montiers** [comment]
I think add one line of workaround for copy the dynamic variable and after it filter is not so bad.

**Comment by DaveBenham** [comment]
> But when I think about it, I can see why filtering dynamic pseudo variables could be a problem - You would have to write a dedicated routine for each individual pseudo variable. It could be done, but I can see why you don't want to.

Actually you already write custom code for all of your `@` getter extensions. Why not do that for all of the dynamic pseudo environment variables?
```
@CD
@CMDEXTVERSION
@CMDCMDLINE
@DATE
@ERRORLEVEL
@HighestNumaNodeNumber
@RANDOM
@TIME
@NUMBER_OF_PROCESSORS
@FIRMWARE_TYPE
@__CD__
@__APPDIR__
```
There would be multiple benefits:
- Filters would become available
- Values become available to `{xxx}` embedded expansion (assuming that is implemented)
- Extensions are immune from environment variable overrides as discussed at #42

**Comment by adoxa** [comment]
I could, but I'd have to either patch cmd so EB can get its dynamic variables, or reverse cmd so I can process them the same way, or have my own versions, different from cmd. Not worth the trouble.
