### ISSUE TITLE
String Spreading bugs and IMO design flaw

### ISSUE THREAD

**Issue by DaveBenham** [carlos-montiers/enhancedbatch#49]
**Bug 1: The string spreading "feature" does not work from the command line**

Batch gives the expected output:

    @echo off
    call eb
    echo "hello"^
     " world" EB=%@enhancedbatch%

-- OUTPUT --

    "hello world" EB=0

Doesn't work from the command line:

```
>eb load

>
>echo "hello"^
More?  " world" EB=%@enhancedbatch%
"hello" " world" EB=0

>
```

**Bug 2: Wrong string spread result**

The following script demonstrates how normal batch handles line continuation with quoted strings vs. how EB string spreading handles the same line continuation with quoted strings.

The test is done with both the ECHO and SET commands.
```
@echo off

call eb unload
call :test "EB:False" "set " ""
call :test "EB:False" "echo" rem
call eb
call :test "EB:True " "set " ""
call :test "EB:True " "echo" rem
exit /b

:test
setlocal enableDelayedExpansion
%~2 var=%~1:%~2 unquoted_1 "quoted_1"^
 unquoted_2 "quoted_2"
%~3 echo var=!var!
```
--OUTPUT--
```
var=EB:False:set  unquoted_1 "quoted_1" unquoted_2 "quoted_2"
var=EB:False:echo unquoted_1 "quoted_1" unquoted_2 "quoted_2"
var=EB:True :set  unquoted_1 "quoted_1quoted_2"
var=EB:True :echo unquoted_1 "quoted_1quoted_2"
```
I don't know what the string spreading result is supposed to be, but the above result cannot possibly be correct.

**Why I think the concept is a design flaw**

I see how string spreading could be useful in some cases. But to blindly apply it to all code is dangerous - it can lead to lots of surprises and or interfere with perfectly reasonable desired results.

The way I found the above bug was via my [JREPL.BAT utility](https://www.dostips.com/forum/viewtopic.php?t=6044) that uses a variant of my [batch argument parser](https://stackoverflow.com/a/8162578/1012053). Within the code I have the following lines to concisely define a bunch of options and their defaults:
```
set ^"/options= /A: /APP: /B: /C: /D:":" /DBUG: /E: /EXC:"" /F:"" /H: /HON:"\x1B[7m" /HOFF:"\x1B[0m" /HU: /I:^
                /INC:"" /J: /JBEG:"" /JBEGLN:"" /JEND:"" /JENDLN:"" /JLIB:"" /JMATCH: /JMATCHQ: /JQ:^
                /K:"" /L: /M: /MATCH: /N:0 /O:"" /OFF:0 /P:"" /PFLAG:"g" /PREPL:"" /R:"" /RTN:"" /S:""^
                /T:"none" /TFLAG:"" /U: /UTF: /V: /VT: /X: /XBYTES: /XBYTESOFF: /XFILE: /XSEQ: /XREG:"" ^"
```
JREPL failed to work while EB was loaded, and it took a while to diagnose what was going on. It broke because /S was incorrectly getting a default of "none", and /T was not defined at all. I don't know if I would still have problems with EB loaded once the bug is fixed, but I can envision lots of scenarios where perfectly reasonable code would be broken by string spreading.

Hypothetically I can see how it would be nice to have string spreading on one or more CALLed extensions. But I understand why it applies to all commands and not a single standard command or CALLed `@extension` - line continuation is handled in [Phase 2](https://stackoverflow.com/a/4095133/1012053), long before your CALL patch point in Phase 6 or standard command patch point in Phase 7.

I vote for removing string spreading. But if you really want to preserve the functionality, it ought to be an option that can be enabled and disabled via a read/write extension like `@stringspread`.

The reason I don't like options like `@stringspread` and `@echooptions` is because an irresponsible developer could leave those options on after their script terminates. Someone else could download and use such a script, and then wonder why their own scripts suddenly stopped working. It could be very difficult to trace what went wrong. I know I struggled a bit figuring out what was wrong with JREPL.

**Comment by carlos-montiers** [comment]
Thanks Dave, I agree on turn this feature optionable (disabled by default), because can also be useful in specific scenario, and also improve for works okay in the command line as in script.

**Comment by adoxa** [comment]
> Bug 1: The string spreading "feature" does not work from the command line

It's implemented at the file level (`ReadFile` hook). Command line will not be supported.

> Bug 2: Wrong string spread result

Fixed.

> I see how string spreading could be useful in some cases. But to blindly apply it to all code is dangerous - it can lead to lots of surprises and or interfere with perfectly reasonable desired results.

I've added a plus sign, so string continuation now occurs if the line ends with `"^+` and the next line begins (ignoring space and tab) with `"`. Since plus doesn't need to be escaped I'd expect such a sequence to be extremely rare.

```batch
c:\Projects\enhancedbatch>type tst.bat
@echo off
call eb
echo first line ^
second line^
 "third &"^+
 " fourth lines" ^
fifth line^
 "sixth, "^+
 "seventh & "^+
 "eighth lines" ^
ninth line

c:\Projects\enhancedbatch>tst.bat
first line second line "third & fourth lines" fifth line "sixth, seventh & eighth lines" ninth line

c:\Projects\enhancedbatch>
```

> The reason I don't like options like `@stringspread` and `@echooptions` is because an irresponsible developer could leave those options on after their script terminates.

That's currently a problem with CMD extensions and delayed expansion, too. We've discussed various ways to handle this (and other settings, like color and opacity), but nothing's come of it, yet. It's a separate issue, please don't continue discussing it here.

**Comment by DaveBenham** [comment]
> > Bug 1: The string spreading "feature" does not work from the command line
> 
> It's implemented at the file level (`ReadFile` hook). Command line will not be supported.

I wondered if that might be the case after I wrote the issue. Makes sense. Thanks.

> > I see how string spreading could be useful in some cases. But to blindly apply it to all code is dangerous - it can lead to lots of surprises and or interfere with perfectly reasonable desired results.
> 
> I've added a plus sign, so string continuation now occurs if the line ends with `"^+` and the next line begins (ignoring space and tab) with `"`. Since plus doesn't need to be escaped I'd expect such a sequence to be extremely rare.

I like it! 👍  I agree `^+` should be extremely rare for the reason you state, and then throw in the `"` requirement - I can't imagine any reasonable existing code line ending with `"^+`. 

> > The reason I don't like options like `@stringspread` and `@echooptions` is because an irresponsible developer could leave those options on after their script terminates.
> 
> That's currently a problem with CMD extensions and delayed expansion, too. We've discussed various ways to handle this (and other settings, like color and opacity), but nothing's come of it, yet. It's a separate issue, please don't continue discussing it here.

I'm cool with that. Thanks

**Comment by DaveBenham** [comment]
I did some testing, and it is even better than I thought!

Not only must the line end with `"^+`, but the first non-whitespace character on the next line must be a quote. If and only if all are true, then the `"+` is removed, and the next line is appended with the leading whitespace and `"` removed.

    echo "string beginning "^+
                "string end on the same line"

--OUTPUT--

    string beginning string end on the same line"

But if the first non-whitespace character on the next line is not `"`, then behavior is standard batch

    echo "string with trailing plus"^+
    echo "another string on the next line"

-- OUTPUT--

    "string with trailing plus"+
    "another string on the next line"

I love it!

I did find one very odd behavior that doesn't make sense to me, but I don't think I really care about it:
```
echo "Part 1 "^+
    "^+
    "echo Part 2 
```
--OUTPUT--
```
"Part 1 ^+    "echo Part 2
```

But put another quote in the middle line and it makes perfect sense:
```
echo "Part 1 "^+
    ""^+
    "echo Part 2 
```
--OUTPUT--
```
"Part 1 echo Part 2
```

**Comment by DaveBenham** [comment]
I think I like the term "string continuation" over "string spreading"

**Comment by adoxa** [comment]
> I did find one very odd behavior that doesn't make sense to me, but I don't think I really care about it:

To maintain file position I insert nulls between the new end of line and the old; this is causing CMD to join the lines.

```batch
c:\Projects\enhancedbatch>type tst.bat|sed s/\x0/^<null^>/
@echo abc<null>
def

c:\Projects\enhancedbatch>tst.bat
abcdef
```

> I think I like the term "string continuation" over "string spreading"

Going back through emails, it looks like I first called it "quote concatenation", then "string concatenation" (like what C does) and now "string continuation" (to match line continuation).

**Comment by carlos-montiers** [comment]
@adoxa Please is possible this next:? add comments in the MyReadFile function for indicate the purpose of some portions of code, like indicate the one that is for provide string continuation.
