### ISSUE TITLE
Echo should interpret all the arguments as text

### ISSUE THREAD

**Issue by carlos-montiers** [carlos-montiers/enhancedbatch#5]
The echo command should interpret all the arguments as text.
`echo on` should print `on`
`echo /?` should print `/?`

For know the status or control it, a new extension with setter and getter should be added: `@echo`
`set @echo=on' should enable the echo.
`set @echo=off' or `set @echo=' should disable the echo.
echo %@echo% should print 'on' or 'off' accordingly to the echo command status.

**Comment by adoxa** [comment]
Added in c7b8acb, although it only uses `0` and `1` (I'll add `on`/`true` and empty/`off`/`false` for all boolean options in a separate commit; they will, however, always get `0` or `1`).
