### ISSUE TITLE
Catching ANSI 'ESC[6n' response 

### ISSUE THREAD

**Issue by lazna** [carlos-montiers/enhancedbatch#53]
Is it possible to avoid such cumbersomness and catch and store 'ESC[6n' reply into a variable?

https://stackoverflow.com/questions/38237304/get-cursor-position-via-windows-10-console-vt-100-escape-sequence

**Comment by adoxa** [comment]
```batch
set $row := @row
set $column := @column
set $row_column := @position
```

**Comment by lazna** [comment]
Thats it! Do it without ANSI did not came on my mind. Closing...
