### ISSUE TITLE
web page unreachable

### ISSUE THREAD

**Issue by lazna** [carlos-montiers/enhancedbatch#60]
Just found that the web page [https://www.enhancedbatch.com/](url) in unreachable. It look like a DNS problem.

**Comment by carlos-montiers** [comment]
Hello @lazna. I will fix it

**Comment by carlos-montiers** [comment]
Hello @lazna. Thanks for the info. I will fix it

**Comment by carlos-montiers** [comment]
Hello @lazna again. Issue fixed. Web page online again
